In [1]:
# !pip install xlrd

Requirement already satisfied: xlrd in /usr/local/lib/python3.7/dist-packages (1.1.0)

In [1]:
!pip install openensembles

Collecting openensembles
  Downloading OpenEnsembles-2.0.0-py3-none-any.whl (53 kB)
     |████████████████████████████████| 53 kB 638 kB/s
Collecting hdbscan==0.8.*
  Downloading hdbscan-0.8.28.tar.gz (5.2 MB)
     |████████████████████████████████| 5.2 MB 11.2 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting numpy==1.19.*
  Downloading numpy-1.19.5-cp37-cp37m-manylinux2010_x86_64.whl (14.8 MB)
     |████████████████████████████████| 14.8 MB 33.8 MB/s
Collecting scikit-learn==0.24.*
  Downloading scikit_learn-0.24.2-cp37-cp37m-manylinux2010_x86_64.whl (22.3 MB)
     |████████████████████████████████| 22.3 MB 1.3 MB/s
Collecting networkx==2.5
  Downloading networkx-2.5-py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 39.5 MB/s
Collecting matplotlib==3.3.*
  Downloading matplotlib-3.3.4-cp37-cp37m-manylinux1_x86_64.whl (11.5 MB)
     |████████████████████████████████| 11.5 MB 25.3 MB/s
Collecting pandas==1.2.*
  Downloading pandas-1.2.5-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (9.9 MB)
     |████████████████████████████████| 9.9 MB 25.5 MB/s
Collecting scipy==1.6.*
  Downloading scipy-1.6.3-cp37-cp37m-manylinux1_x86_64.whl (27.4 MB)
     |████████████████████████████████| 27.4 MB 142 kB/s
Requirement already satisfied: cython>=0.27 in /usr/local/lib/python3.7/dist-packages (from hdbscan==0.8.*->openensembles) (0.29.30)
Collecting hdbscan==0.8.*
  Downloading hdbscan-0.8.27.tar.gz (6.4 MB)
     |████████████████████████████████| 6.4 MB 32.1 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.7/dist-packages (from hdbscan==0.8.*->openensembles) (1.1.0)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from hdbscan==0.8.*->openensembles) (1.15.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /usr/local/lib/python3.7/dist-packages (from matplotlib==3.3.*->openensembles) (3.0.9)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib==3.3.*->openensembles) (1.4.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib==3.3.*->openensembles) (0.11.0)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib==3.3.*->openensembles) (2.8.2)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.7/dist-packages (from matplotlib==3.3.*->openensembles) (7.1.2)
Requirement already satisfied: decorator>=4.3.0 in /usr/local/lib/python3.7/dist-packages (from networkx==2.5->openensembles) (4.4.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas==1.2.*->openensembles) (2022.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn==0.24.*->openensembles) (3.1.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from kiwisolver>=1.0.1->matplotlib==3.3.*->openensembles) (4.2.0)
Building wheels for collected packages: hdbscan
  Building wheel for hdbscan (PEP 517) ... done
  Created wheel for hdbscan: filename=hdbscan-0.8.27-cp37-cp37m-linux_x86_64.whl size=2311903 sha256=aa7d66b34367a1c031bc511ab20ab7fc8d4b770c36f4c391a47d1c810f79307f
  Stored in directory: /root/.cache/pip/wheels/73/5f/2f/9a259b84003b84847c259779206acecabb25ab56f1506ee72b
Successfully built hdbscan
Installing collected packages: numpy, scipy, scikit-learn, pandas, networkx, matplotlib, hdbscan, openensembles
  Attempting uninstall: numpy
    Found existing installation: numpy 1.21.6
    Uninstalling numpy-1.21.6:
      Successfully uninstalled numpy-1.21.6
  Attempting uninstall: scipy
    Found existing installation: scipy 1.4.1
    Uninstalling scipy-1.4.1:
      Successfully uninstalled scipy-1.4.1
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.0.2
    Uninstalling scikit-learn-1.0.2:
      Successfully uninstalled scikit-learn-1.0.2
  Attempting uninstall: pandas
    Found existing installation: pandas 1.3.5
    Uninstalling pandas-1.3.5:
      Successfully uninstalled pandas-1.3.5
  Attempting uninstall: networkx
    Found existing installation: networkx 2.6.3
    Uninstalling networkx-2.6.3:
      Successfully uninstalled networkx-2.6.3
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.2.2
    Uninstalling matplotlib-3.2.2:
      Successfully uninstalled matplotlib-3.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.8.0+zzzcolab20220506162203 requires tf-estimator-nightly==2.8.0.dev2021122109, which is not installed.
yellowbrick 1.4 requires scikit-learn>=1.0.0, but you have scikit-learn 0.24.2 which is incompatible.
xarray-einstats 0.2.2 requires numpy>=1.21, but you have numpy 1.19.5 which is incompatible.
tensorflow 2.8.0+zzzcolab20220506162203 requires numpy>=1.20, but you have numpy 1.19.5 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.
Successfully installed hdbscan-0.8.27 matplotlib-3.3.4 networkx-2.5 numpy-1.19.5 openensembles-2.0.0 pandas-1.2.5 scikit-learn-0.24.2 scipy-1.6.3

In [86]:
# 第 1 部分
# 載入函式庫
import matplotlib.pyplot as plt
import numpy as np
import openensembles as oe 
import pandas as pd
from sklearn import metrics
# from sklearn.metrics.cluster import silhouette_score  # 輪廓係數 (樣本集,聚類標籤)


# 載入資料集
# data = pd.read_excel('/content/WHR.xls')
# regs = pd.read_excel('/content/REG.xls')

regs = pd.read_excel("/content/REG.xlsx")
data = pd.read_excel('/content/WHR.xlsx')

# 使用 2017 年的資料並填補缺少的項目
recents = data[data.Year == 2017]
recents = recents.dropna(axis=1, how="all") # axis=1: 刪除包含缺失值的列; how="all": 所有的值都缺失，才刪除行或列
recents = recents.fillna(recents.median())

# 使用以下特徵
columns = ['Log GDP per capita',
           'Social support',
           'Healthy life expectancy at birth',
           'Freedom to make life choices',
           'Generosity',
           'Perceptions of corruption',
           'Positive affect',
           'Negative affect',
           'Confidence in national government',
           'Democratic Quality',
           'Delivery Quality']

# 特徵正規化
normalized = recents[columns]
normalized = normalized - normalized.mean()
normalized = normalized / normalized.std()


# 建立 data 物件
cluster_data = oe.data(normalized[columns], columns)

In [89]:
# regs.head()

  Country name          Region
0      Finland  Western Europe
1      Denmark  Western Europe
2  Switzerland  Western Europe
3      Iceland  Western Europe
4  Netherlands  Western Europe

In [90]:
# data.head()

,Country name,Year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,...,GINI index (World Bank estimate),"GINI index (World Bank estimate), average 2000-16","gini of household income reported in Gallup, by wp5-year","Most people can be trusted, Gallup","Most people can be trusted, WVS round 1981-1984","Most people can be trusted, WVS round 1989-1993","Most people can be trusted, WVS round 1994-1998","Most people can be trusted, WVS round 1999-2004","Most people can be trusted, WVS round 2005-2009","Most people can be trusted, WVS round 2010-2014"
0,Afghanistan,2008,3.723590,7.168690,0.450662,50.799999,0.718114,0.177889,0.881686,0.517637,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,2009,4.401778,7.333790,0.552308,51.200001,0.678896,0.200178,0.850035,0.583926,...,NaN,NaN,0.441906,0.286315,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,2010,4.758381,7.386629,0.539075,51.599998,0.600127,0.134353,0.706766,0.618265,...,NaN,NaN,0.327318,0.275833,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,2011,3.831719,7.415019,0.521104,51.919998,0.495901,0.172137,0.731109,0.611387,...,NaN,NaN,0.336764,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,2012,3.782938,7.517126,0.520637,52.240002,0.530935,0.244273,0.775620,0.710385,...,NaN,NaN,0.344540,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [91]:
# recents.head()

,Country name,Year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,...,Standard deviation/Mean of ladder by country-year,GINI index (World Bank estimate),"GINI index (World Bank estimate), average 2000-16","gini of household income reported in Gallup, by wp5-year","Most people can be trusted, WVS round 1981-1984","Most people can be trusted, WVS round 1989-1993","Most people can be trusted, WVS round 1994-1998","Most people can be trusted, WVS round 1999-2004","Most people can be trusted, WVS round 2005-2009","Most people can be trusted, WVS round 2010-2014"
9,Afghanistan,2017,2.661718,7.497755,0.490880,52.799999,0.427011,-0.112198,0.954393,0.496349,...,0.546283,0.38,0.371833,0.286599,0.393898,0.287485,0.232353,0.231145,0.202638,0.193531
20,Albania,2017,4.639548,9.376145,0.637698,68.400002,0.749611,-0.032643,0.876135,0.669241,...,0.578096,0.38,0.303250,0.410488,0.393898,0.287485,0.243243,0.232000,0.202638,0.193531
27,Algeria,2017,5.248912,9.540639,0.806754,65.699997,0.436670,-0.191522,0.699774,0.641980,...,0.388607,0.38,0.276000,0.527556,0.393898,0.287485,0.232353,0.107644,0.202638,0.179286
44,Argentina,2017,6.039330,9.848709,0.906699,68.599998,0.831966,-0.182600,0.841052,0.809423,...,0.398940,0.38,0.460938,0.394176,0.270073,0.223553,0.170844,0.150154,0.174058,0.193531
57,Armenia,2017,4.287736,9.081095,0.697925,66.599998,0.613697,-0.133958,0.864683,0.625014,...,0.542333,0.38,0.319250,0.478877,0.393898,0.287485,0.235000,0.231145,0.202638,0.109136

In [92]:
# normalized.head()

,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect,Confidence in national government,Democratic Quality,Delivery Quality
9,-1.525335,-2.582025,-1.616112,-2.787181,-0.670131,1.244764,-1.930496,0.887859,-1.227951,-1.995923,-1.455803
20,0.061344,-1.376442,0.592396,-0.245670,-0.159174,0.804452,-0.331614,0.473243,-0.218758,0.477921,-0.128744
27,0.200292,0.011740,0.210154,-2.711081,-1.179601,-0.187826,-0.583722,-0.026994,-0.095819,-0.911041,-0.825542
44,0.460520,0.832430,0.620710,0.403142,-1.122297,0.607065,0.964764,0.006306,-1.000749,0.536029,-0.156900
57,-0.187885,-0.881897,0.337568,-1.316428,-0.809886,0.740022,-0.740620,1.616748,-1.301256,-0.577781,-0.131407

In [93]:
# 測試不同的子群數
Ks = [2, 4, 6, 8, 10, 12, 14]
# 測試不同的基學習器個數
sizes = [5, 10, 20, 50]
for K in Ks:
    for ensemble_size in sizes:
      print('子群數'+str(K),'基學習器個數'+str(ensemble_size))

子群數2 基學習器個數5
子群數2 基學習器個數10
子群數2 基學習器個數20
子群數2 基學習器個數50
子群數4 基學習器個數5
子群數4 基學習器個數10
子群數4 基學習器個數20
子群數4 基學習器個數50
子群數6 基學習器個數5
子群數6 基學習器個數10
子群數6 基學習器個數20
子群數6 基學習器個數50
子群數8 基學習器個數5
子群數8 基學習器個數10
子群數8 基學習器個數20
子群數8 基學習器個數50
子群數10 基學習器個數5
子群數10 基學習器個數10
子群數10 基學習器個數20
子群數10 基學習器個數50
子群數12 基學習器個數5
子群數12 基學習器個數10
子群數12 基學習器個數20
子群數12 基學習器個數50
子群數14 基學習器個數5
子群數14 基學習器個數10
子群數14 基學習器個數20
子群數14 基學習器個數50

In [23]:
# 使用openensembles共線鏈(Co-occurrence Linkage)集成非監督式學習的基學習器
# 共線矩陣顯示任何2筆資料被基學習器分在相同子群的頻率
# 共線鏈將共線矩陣視為相似度矩陣，接著使用階層式分群

In [94]:
# normalized[columns].tail()

,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect,Confidence in national government,Democratic Quality,Delivery Quality
1653,0.114688,0.743585,0.295097,-1.144621,-1.272810,0.623476,0.189981,0.795491,-1.330919,-1.214076,-1.766779
1666,-0.486348,0.191504,0.493296,0.250016,-0.146525,0.275464,0.144417,-0.134249,-0.095819,-0.481695,-0.227157
1677,0.159314,-0.129486,-1.177241,-1.462225,-0.146525,0.275464,-2.311199,0.043362,-1.296707,-2.493740,-1.700391
1689,-0.921015,-0.505577,-1.332970,0.333832,0.878387,0.035916,-0.189360,1.063515,1.112393,0.009510,-0.492173
1702,-1.481633,-0.420235,-1.304655,-0.220340,-0.396986,0.101562,0.937074,-0.742995,0.935992,-0.979448,-1.367561

In [35]:
# preds.labels

{'co_occ_linkage': array([ 4, 11, 10, 11, 10, 14, 14, 10, 11,  8, 10, 14,  3,  8, 11,  7, 10,
         9,  4,  2,  4, 14,  1,  1, 12, 11, 11,  6,  4, 12, 12, 14, 12, 14,
        10, 11,  2, 10, 12,  5, 14, 14,  5,  3,  8, 14,  6, 14,  8,  4,  3,
        11, 13,  9, 14,  5,  2, 10,  5, 14, 14, 14,  1, 11, 13, 10,  8,  5,
         8,  9,  8,  5,  9, 10,  1,  3,  2,  9, 14, 11,  5,  6,  4, 14,  6,
         9, 11,  8,  2, 11, 10,  4,  5,  6,  2, 14, 14, 11,  4,  1, 14,  5,
        10, 12, 10, 11,  2, 12, 14,  9,  8,  5, 10,  5, 11,  1, 13, 12, 12,
         6, 14,  4, 14, 11, 14, 14,  9,  8,  6, 11,  3,  8, 10, 10,  2,  3,
         8,  9, 14, 12, 12,  8, 10, 11,  6,  3,  3], dtype=int32)}

In [95]:
# 第 2 部分程式
# 建立集成模型，測試2,4,6,8,10,12,14不同的子群數，同時也測試5,10,20,50個基學習器
np.random.seed(123456)
results = {'K':[], 'size':[], 'silhouette': []}
# 測試不同的子群數
Ks = [2, 4, 6, 8, 10, 12, 14]
# 測試不同的基學習器個數
sizes = [5, 10, 20, 50]
for K in Ks:
    for ensemble_size in sizes:
        # 初始化基學習器
        ensemble = oe.cluster(cluster_data)
        for i in range(ensemble_size):
            # 訓練基學習器
            name = f'kmeans_{ensemble_size}_{i}'
            ensemble.cluster('parent', 'kmeans', name, K)

        # 使用共現鏈組成所有基學習器的輸出
        preds = ensemble.finish_co_occ_linkage(threshold = 0.5)
        print(f'K: {K}, size {ensemble_size}:', end=' ')
        # 計算輪廓係數
        silhouette = metrics.silhouette_score(recents[columns],preds.labels['co_occ_linkage']) #輪廓係數  (X, labels)(樣本集,聚類標籤)
        print('%.2f' % silhouette)
        results['K'].append(K)
        results['size'].append(ensemble_size)
        results['silhouette'].append(silhouette)
        
results_df = pd.DataFrame(results)
cross = pd.crosstab(results_df.K,
                    results_df['size'], 
                    results_df['silhouette'],
                    aggfunc=lambda x: x)
print(cross)

K: 2, size 5: 0.26
K: 2, size 10: 0.26
K: 2, size 20: 0.26
K: 2, size 50: 0.26
K: 4, size 5: 0.26
K: 4, size 10: 0.26
K: 4, size 20: 0.26
K: 4, size 50: 0.26
K: 6, size 5: 0.20
K: 6, size 10: 0.21
K: 6, size 20: 0.21
K: 6, size 50: 0.21
K: 8, size 5: 0.16
K: 8, size 10: 0.10
K: 8, size 20: 0.12
K: 8, size 50: 0.10
K: 10, size 5: 0.12
K: 10, size 10: 0.12
K: 10, size 20: 0.14
K: 10, size 50: 0.10
K: 12, size 5: 0.12
K: 12, size 10: 0.11
K: 12, size 20: 0.16
K: 12, size 50: 0.13
K: 14, size 5: 0.14
K: 14, size 10: 0.10
K: 14, size 20: 0.11
K: 14, size 50: 0.13
size        5         10        20        50
K
2     0.263043  0.263043  0.263043  0.263043
4     0.256716  0.258508  0.256716  0.256716
6     0.200754  0.213175  0.210667  0.211958
8     0.160993  0.097967  0.119572  0.097516
10    0.118861  0.116659  0.141408  0.104762
12    0.123976  0.108394  0.155766  0.131018
14    0.137106  0.097043  0.106218  0.132492

In [96]:
results_df.tail()

     K  size  silhouette
23  12    50    0.131018
24  14     5    0.137106
25  14    10    0.097043
26  14    20    0.106218
27  14    50    0.132492

In [97]:
pd.crosstab(results_df['K'],
                    results_df['size'], 
                    results_df['silhouette'],
                    aggfunc=lambda x: x)

size        5         10        20        50
K
2     0.263043  0.263043  0.263043  0.263043
4     0.256716  0.258508  0.256716  0.256716
6     0.200754  0.213175  0.210667  0.211958
8     0.160993  0.097967  0.119572  0.097516
10    0.118861  0.116659  0.141408  0.104762
12    0.123976  0.108394  0.155766  0.131018
14    0.137106  0.097043  0.106218  0.132492