In [1]:
# !pip install xlrd

Requirement already satisfied: xlrd in /usr/local/lib/python3.7/dist-packages (1.1.0)

用正規化特徵、子群數為10、基學習器數量為10來做分群，使用k-means演算法，並將集群模型做的分群結果謝入資料集。並根據每一項特徵，畫出該特徵在2個子群的平均數長條圖。長條圖中的長條排序方法，是根據該子群的"生活階梯"由小到大排列。

In [1]:
!pip install openensembles

Collecting openensembles
  Downloading OpenEnsembles-2.0.0-py3-none-any.whl (53 kB)
     |████████████████████████████████| 53 kB 1.5 MB/s
Collecting numpy==1.19.*
  Downloading numpy-1.19.5-cp37-cp37m-manylinux2010_x86_64.whl (14.8 MB)
     |████████████████████████████████| 14.8 MB 32.6 MB/s
Collecting scikit-learn==0.24.*
  Downloading scikit_learn-0.24.2-cp37-cp37m-manylinux2010_x86_64.whl (22.3 MB)
     |████████████████████████████████| 22.3 MB 67.0 MB/s
Collecting pandas==1.2.*
  Downloading pandas-1.2.5-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (9.9 MB)
     |████████████████████████████████| 9.9 MB 42.2 MB/s
Collecting hdbscan==0.8.*
  Downloading hdbscan-0.8.28.tar.gz (5.2 MB)
     |████████████████████████████████| 5.2 MB 54.7 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting scipy==1.6.*
  Downloading scipy-1.6.3-cp37-cp37m-manylinux1_x86_64.whl (27.4 MB)
     |████████████████████████████████| 27.4 MB 1.3 MB/s
Collecting matplotlib==3.3.*
  Downloading matplotlib-3.3.4-cp37-cp37m-manylinux1_x86_64.whl (11.5 MB)
     |████████████████████████████████| 11.5 MB 47.8 MB/s
Collecting networkx==2.5
  Downloading networkx-2.5-py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 43.5 MB/s
Collecting hdbscan==0.8.*
  Downloading hdbscan-0.8.27.tar.gz (6.4 MB)
     |████████████████████████████████| 6.4 MB 40.9 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.7/dist-packages (from hdbscan==0.8.*->openensembles) (1.1.0)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from hdbscan==0.8.*->openensembles) (1.15.0)
Requirement already satisfied: cython>=0.27 in /usr/local/lib/python3.7/dist-packages (from hdbscan==0.8.*->openensembles) (0.29.30)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib==3.3.*->openensembles) (2.8.2)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.7/dist-packages (from matplotlib==3.3.*->openensembles) (7.1.2)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /usr/local/lib/python3.7/dist-packages (from matplotlib==3.3.*->openensembles) (3.0.9)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib==3.3.*->openensembles) (1.4.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib==3.3.*->openensembles) (0.11.0)
Requirement already satisfied: decorator>=4.3.0 in /usr/local/lib/python3.7/dist-packages (from networkx==2.5->openensembles) (4.4.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas==1.2.*->openensembles) (2022.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn==0.24.*->openensembles) (3.1.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from kiwisolver>=1.0.1->matplotlib==3.3.*->openensembles) (4.2.0)
Building wheels for collected packages: hdbscan
  Building wheel for hdbscan (PEP 517) ... done
  Created wheel for hdbscan: filename=hdbscan-0.8.27-cp37-cp37m-linux_x86_64.whl size=2311923 sha256=7acc0b09bb1dab46b11762de0ac7d5f3ea6b83e296cb2b06178a141771e174dd
  Stored in directory: /root/.cache/pip/wheels/73/5f/2f/9a259b84003b84847c259779206acecabb25ab56f1506ee72b
Successfully built hdbscan
Installing collected packages: numpy, scipy, scikit-learn, pandas, networkx, matplotlib, hdbscan, openensembles
  Attempting uninstall: numpy
    Found existing installation: numpy 1.21.6
    Uninstalling numpy-1.21.6:
      Successfully uninstalled numpy-1.21.6
  Attempting uninstall: scipy
    Found existing installation: scipy 1.4.1
    Uninstalling scipy-1.4.1:
      Successfully uninstalled scipy-1.4.1
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.0.2
    Uninstalling scikit-learn-1.0.2:
      Successfully uninstalled scikit-learn-1.0.2
  Attempting uninstall: pandas
    Found existing installation: pandas 1.3.5
    Uninstalling pandas-1.3.5:
      Successfully uninstalled pandas-1.3.5
  Attempting uninstall: networkx
    Found existing installation: networkx 2.6.3
    Uninstalling networkx-2.6.3:
      Successfully uninstalled networkx-2.6.3
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.2.2
    Uninstalling matplotlib-3.2.2:
      Successfully uninstalled matplotlib-3.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.8.0+zzzcolab20220506162203 requires tf-estimator-nightly==2.8.0.dev2021122109, which is not installed.
yellowbrick 1.4 requires scikit-learn>=1.0.0, but you have scikit-learn 0.24.2 which is incompatible.
xarray-einstats 0.2.2 requires numpy>=1.21, but you have numpy 1.19.5 which is incompatible.
tensorflow 2.8.0+zzzcolab20220506162203 requires numpy>=1.20, but you have numpy 1.19.5 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.
Successfully installed hdbscan-0.8.27 matplotlib-3.3.4 networkx-2.5 numpy-1.19.5 openensembles-2.0.0 pandas-1.2.5 scikit-learn-0.24.2 scipy-1.6.3

In [24]:
# 第 1 部分
# 載入函式庫

 
import matplotlib.pyplot as plt
import numpy as np
import openensembles as oe 
import pandas as pd
from sklearn import metrics
# from sklearn.metrics.cluster import silhouette_score  # 輪廓係數 (樣本集,聚類標籤)


# 載入資料集
# data = pd.read_excel('/content/WHR.xls')
# regs = pd.read_excel('/content/REG.xls')

regs = pd.read_excel("/content/REG.xlsx")
data = pd.read_excel('/content/WHR.xlsx')

# 使用 2017 年的資料並填補缺少的項目
recents = data[data.Year == 2017]
recents = recents.dropna(axis=1, how="all") # axis=1: 刪除包含缺失值的列; how="all": 所有的值都缺失，才刪除行或列
recents = recents.fillna(recents.median())

# 使用以下特徵
columns = ['Log GDP per capita',
           'Social support',
           'Healthy life expectancy at birth',
           'Freedom to make life choices',
           'Generosity',
           'Perceptions of corruption',
           'Positive affect',
           'Negative affect',
           'Confidence in national government',
           'Democratic Quality',
           'Delivery Quality']

# 特徵正規化
normalized = recents[columns]
normalized = normalized - normalized.mean()
normalized = normalized / normalized.std()


# 建立 data 物件
cluster_data = oe.data(normalized[columns], columns)

In [25]:
# regs.head()

  Country name          Region
0      Finland  Western Europe
1      Denmark  Western Europe
2  Switzerland  Western Europe
3      Iceland  Western Europe
4  Netherlands  Western Europe

In [26]:
# data.head()

,Country name,Year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,...,GINI index (World Bank estimate),"GINI index (World Bank estimate), average 2000-16","gini of household income reported in Gallup, by wp5-year","Most people can be trusted, Gallup","Most people can be trusted, WVS round 1981-1984","Most people can be trusted, WVS round 1989-1993","Most people can be trusted, WVS round 1994-1998","Most people can be trusted, WVS round 1999-2004","Most people can be trusted, WVS round 2005-2009","Most people can be trusted, WVS round 2010-2014"
0,Afghanistan,2008,3.723590,7.168690,0.450662,50.799999,0.718114,0.177889,0.881686,0.517637,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,2009,4.401778,7.333790,0.552308,51.200001,0.678896,0.200178,0.850035,0.583926,...,NaN,NaN,0.441906,0.286315,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,2010,4.758381,7.386629,0.539075,51.599998,0.600127,0.134353,0.706766,0.618265,...,NaN,NaN,0.327318,0.275833,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,2011,3.831719,7.415019,0.521104,51.919998,0.495901,0.172137,0.731109,0.611387,...,NaN,NaN,0.336764,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,2012,3.782938,7.517126,0.520637,52.240002,0.530935,0.244273,0.775620,0.710385,...,NaN,NaN,0.344540,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
# recents.head()

,Country name,Year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,...,Standard deviation/Mean of ladder by country-year,GINI index (World Bank estimate),"GINI index (World Bank estimate), average 2000-16","gini of household income reported in Gallup, by wp5-year","Most people can be trusted, WVS round 1981-1984","Most people can be trusted, WVS round 1989-1993","Most people can be trusted, WVS round 1994-1998","Most people can be trusted, WVS round 1999-2004","Most people can be trusted, WVS round 2005-2009","Most people can be trusted, WVS round 2010-2014"
9,Afghanistan,2017,2.661718,7.497755,0.490880,52.799999,0.427011,-0.112198,0.954393,0.496349,...,0.546283,0.38,0.371833,0.286599,0.393898,0.287485,0.232353,0.231145,0.202638,0.193531
20,Albania,2017,4.639548,9.376145,0.637698,68.400002,0.749611,-0.032643,0.876135,0.669241,...,0.578096,0.38,0.303250,0.410488,0.393898,0.287485,0.243243,0.232000,0.202638,0.193531
27,Algeria,2017,5.248912,9.540639,0.806754,65.699997,0.436670,-0.191522,0.699774,0.641980,...,0.388607,0.38,0.276000,0.527556,0.393898,0.287485,0.232353,0.107644,0.202638,0.179286
44,Argentina,2017,6.039330,9.848709,0.906699,68.599998,0.831966,-0.182600,0.841052,0.809423,...,0.398940,0.38,0.460938,0.394176,0.270073,0.223553,0.170844,0.150154,0.174058,0.193531
57,Armenia,2017,4.287736,9.081095,0.697925,66.599998,0.613697,-0.133958,0.864683,0.625014,...,0.542333,0.38,0.319250,0.478877,0.393898,0.287485,0.235000,0.231145,0.202638,0.109136

In [28]:
# normalized.head()

,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect,Confidence in national government,Democratic Quality,Delivery Quality
9,-1.525335,-2.582025,-1.616112,-2.787181,-0.670131,1.244764,-1.930496,0.887859,-1.227951,-1.995923,-1.455803
20,0.061344,-1.376442,0.592396,-0.245670,-0.159174,0.804452,-0.331614,0.473243,-0.218758,0.477921,-0.128744
27,0.200292,0.011740,0.210154,-2.711081,-1.179601,-0.187826,-0.583722,-0.026994,-0.095819,-0.911041,-0.825542
44,0.460520,0.832430,0.620710,0.403142,-1.122297,0.607065,0.964764,0.006306,-1.000749,0.536029,-0.156900
57,-0.187885,-0.881897,0.337568,-1.316428,-0.809886,0.740022,-0.740620,1.616748,-1.301256,-0.577781,-0.131407

In [8]:
# # 測試不同的子群數
# Ks = [2, 4, 6, 8, 10, 12, 14]
# # 測試不同的基學習器個數
# sizes = [5, 10, 20, 50]
# for K in Ks:
#     for ensemble_size in sizes:
#       print('子群數'+str(K),'基學習器個數'+str(ensemble_size))

子群數2 基學習器個數5
子群數2 基學習器個數10
子群數2 基學習器個數20
子群數2 基學習器個數50
子群數4 基學習器個數5
子群數4 基學習器個數10
子群數4 基學習器個數20
子群數4 基學習器個數50
子群數6 基學習器個數5
子群數6 基學習器個數10
子群數6 基學習器個數20
子群數6 基學習器個數50
子群數8 基學習器個數5
子群數8 基學習器個數10
子群數8 基學習器個數20
子群數8 基學習器個數50
子群數10 基學習器個數5
子群數10 基學習器個數10
子群數10 基學習器個數20
子群數10 基學習器個數50
子群數12 基學習器個數5
子群數12 基學習器個數10
子群數12 基學習器個數20
子群數12 基學習器個數50
子群數14 基學習器個數5
子群數14 基學習器個數10
子群數14 基學習器個數20
子群數14 基學習器個數50

In [23]:
# 使用openensembles共線鏈(Co-occurrence Linkage)集成非監督式學習的基學習器
# 共線矩陣顯示任何2筆資料被基學習器分在相同子群的頻率
# 共線鏈將共線矩陣視為相似度矩陣，接著使用階層式分群

In [29]:
# 第 2 部分程式
# 建立集成模型
ensemble = oe.cluster(cluster_data)
for i in range(10):
    name = f'kmeans({i}-tsne'
    ensemble.cluster('parent', 'kmeans', name, 10) # 子群數 10

# 使用共現鏈組成所有基學習器的輸出
preds = ensemble.finish_co_occ_linkage(threshold=0.5)

In [31]:
# preds.labels

{'co_occ_linkage': array([ 4, 12, 11,  8, 11,  1,  1, 12,  9,  5, 11,  3,  6, 12, 11, 13,  8,
         2,  6,  5,  6,  1,  4,  4,  3,  9,  8,  6,  6,  3,  2,  3,  2,  1,
         8,  9, 10,  8,  3,  7,  1,  3, 11,  5, 12,  1,  7, 11,  9,  6,  6,
         9,  1,  2,  3,  7,  5, 10,  4,  1,  2,  2,  6,  8,  3, 12,  9,  5,
         9,  9,  9,  5,  2, 11,  7,  6, 10,  2,  1, 11,  6,  6,  6,  1, 11,
         3,  8, 11,  2, 11, 12,  6,  5, 13,  7,  1,  1,  9,  6,  7,  1,  6,
        11,  8,  8,  8, 13,  2,  2,  8,  9,  5,  9,  7, 11,  6,  1,  2,  2,
         8,  2,  4,  2,  9,  1,  1,  3,  5,  5,  9,  6,  8, 11, 11, 10,  6,
        11,  3,  1,  3,  3,  5, 11,  9, 10,  7,  7], dtype=int32)}

In [48]:
# 第 3 部分程式
# 分析成果

# 將「生活階梯」資料集
columns = ['Life Ladder',
           'Log GDP per capita',
           'Social support',
           'Healthy life expectancy at birth',
           'Freedom to make life choices',
           'Generosity',
           'Perceptions of corruption',
           'Positive affect',
           'Negative affect',
           'Confidence in national government',
           'Democratic Quality',
           'Delivery Quality']

# 將預測值加入資料集
recents['Cluster'] = preds.labels['co_occ_linkage']
grouped = recents.groupby('Cluster')

# 計算平均值
means = grouped.mean()[columns]

# 建立長條圖
def create_bar(col, nc, nr, index):
    plt.subplot(nc, nr, index)
    values = means.sort_values('Life Ladder')[col]
    values.plot(kind='bar')
    plt.title(col[:18])
    
# 繪製每項特徵
plt.figure(figsize = (20, 60))
plt.subplots_adjust(hspace=0.4)
i = 1
for col in columns:
    create_bar(col, 3, 4, i)
    i += 1
plt.show()

# 列出每個子群的國家
for index, row in recents.iterrows():
    print(row['Country name'], row['Cluster'])

ImportError: ignored

Afghanistan 4
Albania 12
Algeria 11
Argentina 8
Armenia 11
Australia 1
Austria 1
Azerbaijan 12
Bahrain 9
Bangladesh 5
Belarus 11
Belgium 3
Benin 6
Bolivia 12
Bosnia and Herzegovina 11
Botswana 13
Brazil 8
Bulgaria 2
Burkina Faso 6
Cambodia 5
Cameroon 6
Canada 1
Central African Republic 4
Chad 4
Chile 3
China 9
Colombia 8
Congo (Brazzaville) 6
Congo (Kinshasa) 6
Costa Rica 3
Croatia 2
Cyprus 3
Czech Republic 2
Denmark 1
Dominican Republic 8
Ecuador 9
Egypt 10
El Salvador 8
Estonia 3
Ethiopia 7
Finland 1
France 3
Gabon 11
Gambia 5
Georgia 12
Germany 1
Ghana 7
Greece 11
Guatemala 9
Guinea 6
Haiti 6
Honduras 9
Hong Kong S.A.R. of China 1
Hungary 2
Iceland 3
India 7
Indonesia 5
Iran 10
Iraq 4
Ireland 1
Israel 2
Italy 2
Ivory Coast 6
Jamaica 8
Japan 3
Jordan 12
Kazakhstan 9
Kenya 5
Kosovo 9
Kuwait 9
Kyrgyzstan 9
Laos 5
Latvia 2
Lebanon 11
Lesotho 7
Liberia 6
Libya 10
Lithuania 2
Luxembourg 1
Macedonia 11
Madagascar 6
Malawi 6
Mali 6
Malta 1
Mauritania 11
Mauritius 3
Mexico 8
Moldova 11
Mongolia 2
Montenegro 11
Morocco 12
Mozambique 6
Myanmar 5
Namibia 13
Nepal 7
Netherlands 1
New Zealand 1
Nicaragua 9
Niger 6
Nigeria 7
Norway 1
Pakistan 6
Palestinian Territories 11
Panama 8
Paraguay 8
Peru 8
Philippines 13
Poland 2
Portugal 2
Romania 8
Russia 9
Rwanda 5
Saudi Arabia 9
Senegal 7
Serbia 11
Sierra Leone 6
Singapore 1
Slovakia 2
Slovenia 2
South Africa 8
South Korea 2
South Sudan 4
Spain 2
Sri Lanka 9
Sweden 1
Switzerland 1
Taiwan Province of China 3
Tajikistan 5
Tanzania 5
Thailand 9
Togo 6
Trinidad and Tobago 8
Tunisia 11
Turkey 11
Turkmenistan 10
Uganda 6
Ukraine 11
United Arab Emirates 3
United Kingdom 1
United States 3
Uruguay 3
Uzbekistan 5
Venezuela 11
Vietnam 9
Yemen 10
Zambia 7
Zimbabwe 7

In [47]:
# 列出每個子群的國家
for index, row in recents.iterrows():
    print(row['Country name'], row['Cluster'])

Afghanistan 4
Albania 12
Algeria 11
Argentina 8
Armenia 11
Australia 1
Austria 1
Azerbaijan 12
Bahrain 9
Bangladesh 5
Belarus 11
Belgium 3
Benin 6
Bolivia 12
Bosnia and Herzegovina 11
Botswana 13
Brazil 8
Bulgaria 2
Burkina Faso 6
Cambodia 5
Cameroon 6
Canada 1
Central African Republic 4
Chad 4
Chile 3
China 9
Colombia 8
Congo (Brazzaville) 6
Congo (Kinshasa) 6
Costa Rica 3
Croatia 2
Cyprus 3
Czech Republic 2
Denmark 1
Dominican Republic 8
Ecuador 9
Egypt 10
El Salvador 8
Estonia 3
Ethiopia 7
Finland 1
France 3
Gabon 11
Gambia 5
Georgia 12
Germany 1
Ghana 7
Greece 11
Guatemala 9
Guinea 6
Haiti 6
Honduras 9
Hong Kong S.A.R. of China 1
Hungary 2
Iceland 3
India 7
Indonesia 5
Iran 10
Iraq 4
Ireland 1
Israel 2
Italy 2
Ivory Coast 6
Jamaica 8
Japan 3
Jordan 12
Kazakhstan 9
Kenya 5
Kosovo 9
Kuwait 9
Kyrgyzstan 9
Laos 5
Latvia 2
Lebanon 11
Lesotho 7
Liberia 6
Libya 10
Lithuania 2
Luxembourg 1
Macedonia 11
Madagascar 6
Malawi 6
Mali 6
Malta 1
Mauritania 11
Mauritius 3
Mexico 8
Moldova 11
Mongolia 2
Montenegro 11
Morocco 12
Mozambique 6
Myanmar 5
Namibia 13
Nepal 7
Netherlands 1
New Zealand 1
Nicaragua 9
Niger 6
Nigeria 7
Norway 1
Pakistan 6
Palestinian Territories 11
Panama 8
Paraguay 8
Peru 8
Philippines 13
Poland 2
Portugal 2
Romania 8
Russia 9
Rwanda 5
Saudi Arabia 9
Senegal 7
Serbia 11
Sierra Leone 6
Singapore 1
Slovakia 2
Slovenia 2
South Africa 8
South Korea 2
South Sudan 4
Spain 2
Sri Lanka 9
Sweden 1
Switzerland 1
Taiwan Province of China 3
Tajikistan 5
Tanzania 5
Thailand 9
Togo 6
Trinidad and Tobago 8
Tunisia 11
Turkey 11
Turkmenistan 10
Uganda 6
Ukraine 11
United Arab Emirates 3
United Kingdom 1
United States 3
Uruguay 3
Uzbekistan 5
Venezuela 11
Vietnam 9
Yemen 10
Zambia 7
Zimbabwe 7